### ISSUE TITLE
Possible Lazy-Man's Approach to Formatting

### ISSUE THREAD

**Issue by pquackenbush** [rsanchez-wsu/fa15-ceg3120#13]
I found within checkStyle that there is an option to use an experimental feature that will keep the checkStyle.xml synced with the eclipse formatter.  I tested this against the NetworkManager class, and the only changes that would need to be made manually are the insertion of JavaDoc, adding curlies to the ifs, and reorg of the imports. (of course most of this could just be my personal settings, but man are the tabs huge :stuck_out_tongue_winking_eye: )

If you merge the HomeownerUIBase branch with your own, not only will you have all the common data objects, but .checkStyle.xml should be set to allow this behavior as well

**Comment by pquackenbush** [comment]
That last commit may cause some major headaches when merging as just about every file was affected... Please merge before any further development to prevent as many merge conflicts as possible. 

Thanks

@LABurn @jakern @emilynovak @laanak08 @BrianTighe

**Comment by samohtj** [comment]
Didn't want to create a new issue, so I'm commenting here.

I've switched checkstyle so that it uses 4 space tabs as opposed to 8, and I have a good reason. With 8 space tabs, some of the lines of code already written stick out past the 100 character limits. Even if the tabs you use are actually 4 spaces, checkstyle still thinks they're 8. So, to prevent us having to split our lines of code and wrap them more than we should have to, I've switched everything so it runs on 4 space tabs.

Is this okay with everybody?

**Comment by jakern** [comment]
No problems here

**Comment by rsanchez-wsu** [comment]
@samohtj I am in agreement.

**Comment by pquackenbush** [comment]
I think we've moved passed this.
